apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-voulme
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStorage:
    volumeID: vol-0bcd84c94545c567
    fsType: ext4
